name: run process

on:
  schedule:
    - cron: '0 5 * * *'  # 6 AM Madrid in winter, 7 AM in summer

  workflow_dispatch:

permissions:
  contents: write  # Permitir push en main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: configure python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: execute main.py
        env:
          GDRIVE_CREDENTIALS_JSON: ${{ secrets.GDRIVE_CREDENTIALS_JSON }}      
          ALPHA_API_KEY: ${{ secrets.ALPHA_API_KEY }}
          GDRIVE_FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          TRADING_ADVISOR_FOLDER_ID: ${{ secrets.FINNHUB_API_KEY }}
          BUY_RECOMMENDATIONS_ID: ${{ secrets.BUY_RECOMMENDATIONS_ID }}
          
          ALPHA_VANTAGE_URL: ${{ vars.ALPHA_VANTAGE_URL }}
          REVENUE_PERCENTAGE: ${{ vars.REVENUE_PERCENTAGE }}      
          SYMBOLS_INTEREST_LIST: ${{ vars.SYMBOLS_INTEREST_LIST }}      
          MAILING_LIST: ${{ vars.MAILING_LIST }}
          GOOGLE_FINANCE_LOSERS_URL: ${{ vars.GOOGLE_FINANCE_LOSERS_URL }}  
          LOG_LEVEL:  ${{ vars.LOG_LEVEL }}   
            
        run: python main.py
